export const FETCHVEHICLES = "FETCHVEHICLES"
export const FETCHCURRENTVEHICLE = "FETCHCURRENTVEHICLE"
export const FETCHLOCATIONS = "FETCHLOCATIONS"
export const FETCHLOCATIONVEHICLES = "FETCHLOCATIONVEHICLES"

