export const ADD_VEHICLE_TYPE = "ADD_VEHICLE_TYPE"
export const DELETE_VEHICLE_TYPE = "DELETE_VEHICLE_TYPE"
export const EDIT_VEHICLE_TYPE = "EDIT_VEHICLE_TYPE"
export const GET_VEHICLE_TYPE = "GET_VEHICLE_TYPE"